//
//  MovieDetailViewController.swift
//  MovieVapp
//
//  Created Haiyan Ma on 04/12/2017.
//  Copyright © 2017 Haiyan Ma. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import UIKit

protocol MovieDetailViewing: class {
    var presenter: MovieDetailPresentation? { get set }
}

class MovieDetailViewController: UIViewController, MovieDetailViewing {

	var presenter: MovieDetailPresentation?

    let nameLabel: UILabel = {
        let lb = UILabel()
        lb.numberOfLines = 1
        lb.textAlignment = .center
        lb.font = UIFont.boldSystemFont(ofSize: 24)
        return lb
    }()

    // MARK: View Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        showMovieDetailOnViewDidLoad()
    }

    // MARK: Setup View Components
    private func setupViews() {
        addMovieNameLabel()
        addNavBarButton()
    }

    private func addMovieNameLabel() {
        view.addSubview(nameLabel)
        nameLabel.fillSuperview()
    }

    private func addNavBarButton() {
        let favoriteButton = UIBarButtonItem(title: "Change Color",
                                             style: .done,
                                             target: self,
                                             action: #selector(tapChangeColorBarButton))
        navigationItem.rightBarButtonItem = favoriteButton
    }

    // MARK: Actions
    private func showMovieDetailOnViewDidLoad() {
        presenter?.showDetailOnViewDidLoad(withMovie: { [weak self] (movie) in
            self?.nameLabel.text = movie.name
            }, noMovie: {
                print("No movie returned, weird!!")
        })
    }

    @objc func tapChangeColorBarButton() {
        let randomColor = UIColor(red: CGFloat(drand48()),
                                  green: CGFloat(drand48()),
                                  blue: CGFloat(drand48()),
                                  alpha: 1)
        presenter?.onChangeColorTapped(changeTo: randomColor)
    }
}
