//
//  MovieDetailViewController.swift
//  MovieVapp
//
//  Created Haiyan Ma on 04/12/2017.
//  Copyright © 2017 Haiyan Ma. All rights reserved.
//
//  Template generated by Haiyan Ma @swiftTsubame
//

import UIKit

protocol MovieDetailViewing: class {
    var presenter: MovieDetailPresentation? { get set }
}

class MovieDetailViewController: UIViewController, MovieDetailViewing {

	var presenter: MovieDetailPresentation?

    let nameLabel: UILabel = {
        let lb = UILabel()
        lb.numberOfLines = 1
        lb.textAlignment = .center
        lb.font = UIFont.boldSystemFont(ofSize: 24)
        return lb
    }()

    // MARK: View Life Cycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupViews()
        showMovieDetail()
    }

    // MARK: Setup View Components
    private func setupViews() {
        addMovieNameLabel()
    }

    private func addMovieNameLabel() {
        view.addSubview(nameLabel)
        nameLabel.fillSuperview()
    }

    // MARK: Actions
    private func showMovieDetail() {
        presenter?.showDetailOnViewDidLoad(withMovie: { [weak self] (movie) in
            self?.nameLabel.text = movie.name
            }, noMovie: {
                print("No movie returned, weird!!")
        })
    }
}
