//
//  MovieDetailPresenter.swift
//  MovieVapp
//
//  Created Haiyan Ma on 04/12/2017.
//  Copyright © 2017 Haiyan Ma. All rights reserved.
//
//  Template generated by Haiyan Ma @SwiftTsubame
//

import Foundation
import UIKit

protocol MovieDetailPresentation: class {
    var interactor: MovieDetailInteraction { get }
    var router: MovieDetailRouting { get }
    func prepareToShowMovieDetail()
    func toggleFavorite()
    var isFavorite: Bool { get }
}

class MovieDetailPresenter: MovieDetailPresentation {

    var interactor: MovieDetailInteraction
    var router: MovieDetailRouting
    weak var viewInterface: MovieDetailViewInterface?
    
    init(interactor: MovieDetailInteraction,
         router: MovieDetailRouting) {
        self.interactor = interactor
        self.router = router
    }

    func prepareToShowMovieDetail() {
        guard let selectedMovie = interactor.movie else {
            viewInterface?.showNoMovieError()
            return
        }
        viewInterface?.showMovieDetail(movie: selectedMovie)
    }
    
    func toggleFavorite() {
        interactor.toggleFavorite()
    }
    
    var isFavorite: Bool {
        return interactor.movie?.isFavorite ?? false
    }
}
