//
//  MovieDetailPresenter.swift
//  MovieVapp
//
//  Created Haiyan Ma on 04/12/2017.
//  Copyright © 2017 Haiyan Ma. All rights reserved.
//
//  Template generated by Haiyan Ma @SwiftTsubame
//

import Foundation
import UIKit

protocol MovieDetailPresentation: class {
    var interactor: MovieDetailInteraction { get }
    var router: MovieDetailRouting { get }
    func showDetailOnViewDidLoad(withMovie: (Movie) -> Void, noMovie: () -> Void)
    func onChangeColorTapped(changeTo color: UIColor)
}

class MovieDetailPresenter: MovieDetailPresentation {
    var interactor: MovieDetailInteraction
    var router: MovieDetailRouting
    weak var listPresenter: MovieListPresentation?

    init(interactor: MovieDetailInteraction,
         router: MovieDetailRouting) {
        self.interactor = interactor
        self.router = router
    }

    func showDetailOnViewDidLoad(withMovie: (Movie) -> Void, noMovie: () -> Void) {
        guard let selectedMovie = interactor.movie else {
            noMovie()
            return
        }
        withMovie(selectedMovie)
    }

    func onChangeColorTapped(changeTo color: UIColor) {
        listPresenter?.changeToNewColor(color: color)
    }
}
